echo -e "runing adult"
./naive_bayes.exe  adult_cv1  > 1_NB_result.txt
./naive_bayes.exe  adult_cv2  >> 1_NB_result.txt
./naive_bayes.exe  adult_cv3  >> 1_NB_result.txt
./naive_bayes.exe  adult_cv4  >> 1_NB_result.txt
./naive_bayes.exe  adult_cv5  >> 1_NB_result.txt
./naive_bayes.exe  adult_cv6  >> 1_NB_result.txt
./naive_bayes.exe  adult_cv7  >> 1_NB_result.txt
./naive_bayes.exe  adult_cv8  >> 1_NB_result.txt
./naive_bayes.exe  adult_cv9  >> 1_NB_result.txt
./naive_bayes.exe  adult_cv10  >> 1_NB_result.txt
echo -e "finished adult" >> 1_NB_result.txt
echo -e "runing car"
./naive_bayes.exe  car_cv1  >> 1_NB_result.txt
./naive_bayes.exe  car_cv2  >> 1_NB_result.txt
./naive_bayes.exe  car_cv3  >> 1_NB_result.txt
./naive_bayes.exe  car_cv4  >> 1_NB_result.txt
./naive_bayes.exe  car_cv5  >> 1_NB_result.txt
./naive_bayes.exe  car_cv6  >> 1_NB_result.txt
./naive_bayes.exe  car_cv7  >> 1_NB_result.txt
./naive_bayes.exe  car_cv8  >> 1_NB_result.txt
./naive_bayes.exe  car_cv9  >> 1_NB_result.txt
./naive_bayes.exe  car_cv10  >> 1_NB_result.txt
echo -e "finished car" >> 1_NB_result.txt
echo -e "runing isolet"
./naive_bayes.exe  isolet_cv1  >> 1_NB_result.txt
./naive_bayes.exe  isolet_cv2  >> 1_NB_result.txt
./naive_bayes.exe  isolet_cv3  >> 1_NB_result.txt
./naive_bayes.exe  isolet_cv4  >> 1_NB_result.txt
./naive_bayes.exe  isolet_cv5  >> 1_NB_result.txt
./naive_bayes.exe  isolet_cv6  >> 1_NB_result.txt
./naive_bayes.exe  isolet_cv7  >> 1_NB_result.txt
./naive_bayes.exe  isolet_cv8  >> 1_NB_result.txt
./naive_bayes.exe  isolet_cv9  >> 1_NB_result.txt
./naive_bayes.exe  isolet_cv10  >> 1_NB_result.txt
echo -e "finished isolet" >> 1_NB_result.txt
echo -e "runing page-blocks"
./naive_bayes.exe  page-blocks_cv1  >> 1_NB_result.txt
./naive_bayes.exe  page-blocks_cv2  >> 1_NB_result.txt
./naive_bayes.exe  page-blocks_cv3  >> 1_NB_result.txt
./naive_bayes.exe  page-blocks_cv4  >> 1_NB_result.txt
./naive_bayes.exe  page-blocks_cv5  >> 1_NB_result.txt
./naive_bayes.exe  page-blocks_cv6  >> 1_NB_result.txt
./naive_bayes.exe  page-blocks_cv7  >> 1_NB_result.txt
./naive_bayes.exe  page-blocks_cv8  >> 1_NB_result.txt
./naive_bayes.exe  page-blocks_cv9  >> 1_NB_result.txt
./naive_bayes.exe  page-blocks_cv10  >> 1_NB_result.txt
echo -e "finished page-blocks" >> 1_NB_result.txt
echo -e "runing winequality"
./naive_bayes.exe  winequality_cv1  >> 1_NB_result.txt
./naive_bayes.exe  winequality_cv2  >> 1_NB_result.txt
./naive_bayes.exe  winequality_cv3  >> 1_NB_result.txt
./naive_bayes.exe  winequality_cv4  >> 1_NB_result.txt
./naive_bayes.exe  winequality_cv5  >> 1_NB_result.txt
./naive_bayes.exe  winequality_cv6  >> 1_NB_result.txt
./naive_bayes.exe  winequality_cv7  >> 1_NB_result.txt
./naive_bayes.exe  winequality_cv8  >> 1_NB_result.txt
./naive_bayes.exe  winequality_cv9  >> 1_NB_result.txt
./naive_bayes.exe  winequality_cv10  >> 1_NB_result.txt
echo -e "finished winequality" >> 1_NB_result.txt